package es.udc.lbd.hermes.model.dataservice;

import java.util.EnumSet;

public enum Method {

	GET_INFORMATION_LINK, AGGREGATE_MEASUREMENT, COMPUTE_ROUTE,
	GET_VEHICLE_LOCATIONS, GET_MEASUREMENTS, GET_DATA_SECTIONS, GET_DRIVER_FEATURES,
	GET_HEART_RATE_DATA, GET_STEPS_DATA, GET_SLEEP_DATA, GET_CONTEXT_DATA, GET_USER_LOCATIONS, GET_USER_ACTIVITIES;
	
	public static EnumSet<Method> smartDriver = EnumSet.of(GET_INFORMATION_LINK, AGGREGATE_MEASUREMENT,
			GET_VEHICLE_LOCATIONS, GET_MEASUREMENTS, GET_DATA_SECTIONS, GET_DRIVER_FEATURES);
	
	public static EnumSet<Method> smartCitizen = EnumSet.of(COMPUTE_ROUTE, GET_HEART_RATE_DATA, 
			GET_STEPS_DATA, GET_SLEEP_DATA, GET_CONTEXT_DATA, GET_USER_LOCATIONS, GET_USER_ACTIVITIES);
	
	public String getName(){		
		return this.name();
	}
}
